SELECT
    id::number AS id,
    TO_TIMESTAMP_NTZ(
        updated_time, 'YYYY-MM-DD"T"HH24:MI:SSTZHTZM'
    ) AS updated_time,
    account_id::number AS account_id,
    campaign_id::number AS campaign_id,
    creative:id::number AS creative_id,
    bid_amount::number AS bid_amount,
    bid_type,
    configured_status,
    conversion_domain,
    TO_TIMESTAMP_NTZ(
        created_time, 'YYYY-MM-DD"T"HH24:MI:SSTZHTZM'
    ) AS created_time,
    effective_status,
    last_updated_by_app_id::number AS last_updated_by_app_id,
    name,
    status,
    adset_id::number AS ad_set_id,
    source_ad_id::number AS ad_source_id,
    bid_info:ACTIONS::number AS bid_info_actions,
    placement_specific_facebook_unsafe_substances,
    placement_specific_instagram_unsafe_substances,
    global_unsafe_substances,
    placement_specific_instagram_personal_attributes,
    global_personal_attributes,
    placement_specific_facebook_personal_attributes,
    placement_specific_instagram_nonexistent_functionality,
    global_nonexistent_functionality,
    placement_specific_facebook_nonexistent_functionality,
    placement_specific_facebook_advertising_policies,
    placement_specific_instagram_advertising_policies,
    global_advertising_policies,
    global_spyware_or_malware,
    placement_specific_instagram_spyware_or_malware,
    placement_specific_facebook_spyware_or_malware,
    placement_specific_instagram_unrealistic_outcomes,
    global_unrealistic_outcomes,
    placement_specific_facebook_unrealistic_outcomes,
    placement_specific_facebook_brand_usage_in_ads,
    global_brand_usage_in_ads,
    global_personal_health_and_appearance,
    placement_specific_facebook_personal_health_and_appearance,
    placement_specific_instagram_personal_health_and_appearance,
    placement_specific_instagram_illegal_products_or_services,
    global_illegal_products_or_services,
    placement_specific_facebook_illegal_products_or_services,
    global_non_functional_landing_page,
    placement_specific_facebook_non_functional_landing_page,
    placement_specific_instagram_non_functional_landing_page,
    placement_specific_instagram_commercial_exploitation_of_crises_and_controversial_events,
    placement_specific_facebook_commercial_exploitation_of_crises_and_controversial_events,
    global_commercial_exploitation_of_crises_and_controversial_events,
    global_discriminatory_practices,
    placement_specific_facebook_discriminatory_practices,
    global_circumventing_systems,
    placement_specific_facebook_circumventing_systems,
    placement_specific_instagram_circumventing_systems,
    placement_specific_facebook_adult_content,
    placement_specific_facebook_sensational_content,
    global_adult_content,
    bid_info:impressions::number AS bid_info_impressions,
    global_sensational_content,
    placement_specific_instagram_adult_content,
    placement_specific_instagram_brand_usage_in_ads,
    placement_specific_instagram_sensational_content,
    placement_specific_facebook_ads_about_social_issues_elections_or_politics,
    placement_specific_instagram_ads_about_social_issues_elections_or_politics,
    global_ads_about_social_issues_elections_or_politics,
    _sdc_batched_at

FROM {{ source('tap_facebook', 'ads') }}
