SELECT HASH,
       ID,
       UPDATED_TIME,
       ACCOUNT_ID,
       CREATED_TIME,
       CREATIVES,
       HEIGHT,
       IS_ASSOCIATED_CREATIVES_IN_ADGROUPS as IS_ASSOCIATED_IN_ADGROUPS,
       NAME,
       ORIGINAL_HEIGHT,
       ORIGINAL_WIDTH,
       PERMALINK_URL,
       STATUS,
       URL,
       URL_128,
       WIDTH,
       _SDC_BATCHED_AT


FROM RYAN_MIRANDA_RAW.MELTANO_FACEBOOK.ADIMAGES