SELECT
    id::number AS id,
    TO_TIMESTAMP_NTZ(
        updated_time, 'YYYY-MM-DD"T"HH24:MI:SSTZHTZM'
    ) AS updated_time,
    campaign_id::number AS campaign_id,
    account_id::number AS account_id,
    asset_feed_id::number AS asset_feed_id,
    bid_amount::number AS bid_amount,
    bid_strategy,
    billing_event,
    budget_remaining::number AS budget_remaining,
    configured_status,
    TO_TIMESTAMP_NTZ(
        created_time, 'YYYY-MM-DD"T"HH24:MI:SSTZHTZM'
    ) AS created_time,
    daily_budget::number AS daily_budget,
    daily_min_spend_target::number AS daily_min_spend_target,
    daily_spend_cap::number AS daily_spend_cap,
    destination_type,
    effective_status,
    TO_TIMESTAMP_NTZ(end_time, 'YYYY-MM-DD"T"HH24:MI:SSTZHTZM') AS end_time,
    instagram_actor_id::number AS instagram_actor_id,
    is_dynamic_creative::boolean AS is_dynamic_creative,
    lifetime_budget::number AS lifetime_budget,
    lifetime_imps::number AS lifetime_imps,
    lifetime_min_spend_target::number AS lifetime_min_spend_target,
    lifetime_spend_cap::number AS lifetime_spend_cap,
    multi_optimization_goal_weight,
    name,
    optimization_goal,
    optimization_sub_event,
    recurring_budget_semantics::boolean AS recurring_budget_semantics,
    review_feedback,
    rf_prediction_id,
    status,
    TO_TIMESTAMP_NTZ(start_time, 'YYYY-MM-DD"T"HH24:MI:SSTZHTZM') AS start_time,
    use_new_app_click::boolean AS use_new_app_click,
    promoted_object_application_id,
    promoted_object_custom_conversion_id::number AS promoted_object_custom_conversion_id,
    promoted_object_custom_event_str,
    promoted_object:custom_event_type::varchar AS promoted_object_custom_event_type,
    promoted_object_event_id::number AS promoted_object_event_id,
    promoted_object_object_store_url,
    promoted_object_offer_id::number AS promoted_object_offer_id,
    promoted_object_offline_conversion_data_set_id::number AS promoted_object_offline_conversion_data_set_id,
    promoted_object_page_id::number AS promoted_object_page_id,
    promoted_object_pixel_aggregation_rule,
    promoted_object:pixel_id::number AS promoted_object_pixel_id,
    promoted_object_pixel_rule,
    promoted_object_place_page_set_id::number AS promoted_object_place_page_set_id,
    promoted_object_product_catalog_id::number AS promoted_object_product_catalog_id,
    promoted_object_product_set_id::number AS promoted_object_product_set_id,
    promoted_object_retention_days,
    learning_stage_info:attribution_windows AS learning_stage_info_attribution_windows,
    learning_stage_info:conversions::number AS learning_stage_info_conversions,
    learning_stage_info:last_sig_edit_ts::number AS learning_stage_info_last_sig_edit_ts,
    learning_stage_info:status::varchar AS learning_stage_info_status,
    targeting_app_install_state,
    targeting:age_max::number AS targeting_age_max,
    targeting:age_min::number AS targeting_age_min,
    targeting:genders AS targeting_genders,
    targeting_behaviors,
    targeting_interests,
    targeting_relationship_statuses,
    targeting_life_events,
    targeting_industries,
    targeting_income,
    targeting_family_statuses,
    targeting_audience_network_positions,
    targeting_connections,
    targeting:device_platforms AS targeting_device_platforms,
    targeting_effective_audience_network_positions,
    targeting_excluded_connections,
    targeting_excluded_publisher_categories,
    targeting_excluded_publisher_list_ids,
    targeting_excluded_user_device,
    targeting:facebook_positions AS targeting_facebook_positions,
    targeting_friends_of_connections,
    targeting:instagram_positions AS targeting_instagram_positions,
    targeting:publisher_platforms AS targeting_publisher_platforms,
    targeting_user_os,
    targeting_user_device,
    targeting_wireless_carrier,
    targeting_education_schools,
    targeting_education_statuses,
    targeting_college_years,
    targeting_education_majors,
    targeting_work_employers,
    targeting_work_positions,
    targeting_locales,
    targeting_user_adclusters,
    targeting_flexible_spec,
    targeting_exclusions,
    targeting:geo_locations.countries AS targeting_geo_locations_countries,
    targeting_geo_locations_regions,
    targeting_geo_locations_cities,
    targeting_geo_locations_zips,
    targeting_geo_locations_places,
    targeting_geo_locations_custom_locations,
    targeting_geo_locations_geo_markets,
    targeting_geo_locations_electoral_district,
    targeting:geo_locations.location_types AS targeting_geo_locations_location_types,
    targeting_geo_locations_country_groups,
    targeting_excluded_geo_locations_countries,
    targeting_excluded_geo_locations_regions,
    targeting_excluded_geo_locations_cities,
    targeting_excluded_geo_locations_zips,
    targeting_excluded_geo_locations_places,
    targeting_excluded_geo_locations_custom_locations,
    targeting_excluded_geo_locations_geo_markets,
    targeting_excluded_geo_locations_electoral_district,
    targeting_excluded_geo_locations_location_types,
    targeting_excluded_geo_locations_country_groups,

    source_adset_id::number AS adset_source_id,
    bid_amount::number AS bid_info_actions,
    bid_info:IMPRESSIONS::number AS bid_info_impressions,
    _sdc_batched_at

FROM {{ source('tap_facebook', 'adsets') }}
