{{
   config(
     materialized='view'
   )
}}

{% set json_column_query %}
select distinct json.key as column_name

FROM {{ source('tap_facebook', 'adsets')}},

lateral flatten(input=>PROMOTED_OBJECT) json
{% endset %}
 
{% set promoted_object_results = run_query(json_column_query) %}

{% if execute %}
{# Return the first column #}
{% set promoted_object_list = promoted_object_results.columns[0].values() %}
{% else %}
{% set promoted_object_list = [] %}
{% endif %}

{% set json_column_query %}
select distinct json.key as column_name

FROM {{ source('tap_facebook', 'adsets')}},

lateral flatten(input=>ATTRIBUTION_SPEC[0]) json
{% endset %}
 
{% set attribution_spec_results = run_query(json_column_query) %}

{% if execute %}
{# Return the first column #}
{% set attribution_spec_list = attribution_spec_results.columns[0].values() %}
{% else %}
{% set attribution_spec_list = [] %}
{% endif %}

{% set json_column_query %}
select distinct json.key as column_name

FROM {{ source('tap_facebook', 'adsets')}},

lateral flatten(input=>LEARNING_STAGE_INFO) json
{% endset %}
 
{% set learning_stage_results = run_query(json_column_query) %}

{% if execute %}
{# Return the first column #}
{% set learning_stage_list = learning_stage_results.columns[0].values() %}
{% else %}
{% set learning_stage_list = [] %}
{% endif %}


select ACCOUNT_ID,
       ADLABELS,
       ASSET_FEED_ID,
       ATTRIBUTION_SPEC,
       BID_INFO,
       BILLING_EVENT,
       BUDGET_REMAINING,
       CAMPAIGN_ATTRIBUTION,
       CAMPAIGN_ID,
       CONFIGURED_STATUS,
       TO_TIMESTAMP_NTZ(CREATED_TIME, 'YYYY-MM-DD"T"HH24:MI:SSTZHTZM') as CREATED_TIME,
       DAILY_BUDGET,
       DAILY_MIN_SPEND_TARGET,
       DAILY_SPEND_CAP,
       DESTINATION_TYPE,
       EFFECTIVE_STATUS,
       END_TIME,
       ID,
       INSTAGRAM_ACTOR_ID,
       IS_DYNAMIC_CREATIVE,
       LEARNING_STAGE_INFO,
       LIFETIME_BUDGET,
       LIFETIME_IMPS,
       MULTI_OPTIMIZATION_GOAL_WEIGHT,
       NAME,
       OPTIMIZATION_GOAL,
       OPTIMIZATION_SUB_EVENT,
       PACING_TYPE,
       PROMOTED_OBJECT,
       RECURRING_BUDGET_SEMANTICS,
       REVIEW_FEEDBACK,
       RF_PREDICTION_ID,
       SOURCE_ADSET_ID,
       START_TIME,
       STATUS,
       TARGETING_OPTIMIZATION_TYPES,
       TO_TIMESTAMP_NTZ(UPDATED_TIME, 'YYYY-MM-DD"T"HH24:MI:SSTZHTZM') as UPDATED_TIME,
       USE_NEW_APP_CLICK,
       _SDC_BATCHED_AT

      /*TODO: Add the following columns:
PROMOTED_OBJECT_APPLICATION_ID 
LEARNING_STAGE_INFO_ATTRIBUTION_WINDOWS
LEARNING_STAGE_INFO_CONVERSIONS
LEARNING_STAGE_INFO_LAST_SIG_EDIT_TS
LEARNING_STAGE_INFO_STATUS
TARGETING_APP_INSTALL_STATE
TARGETING_AGE_MAX
TARGETING_AGE_MIN
TARGETING_GENDERS
TARGETING_BEHAVIORS
TARGETING_INTERESTS
TARGETING_RELATIONSHIP_STATUSES
TARGETING_LIFE_EVENTS
TARGETING_INDUSTRIES
TARGETING_INCOME
TARGETING_FAMILY_STATUSES
TARGETING_AUDIENCE_NETWORK_POSITIONS
TARGETING_CONNECTIONS
TARGETING_DEVICE_PLATFORMS
TARGETING_EFFECTIVE_AUDIENCE_NETWORK_POSITIONS
TARGETING_EXCLUDED_CONNECTIONS
TARGETING_EXCLUDED_PUBLISHER_CATEGORIES
TARGETING_EXCLUDED_PUBLISHER_LIST_IDS
TARGETING_EXCLUDED_USER_DEVICE
TARGETING_FACEBOOK_POSITIONS
TARGETING_FRIENDS_OF_CONNECTIONS
TARGETING_INSTAGRAM_POSITIONS
TARGETING_PUBLISHER_PLATFORMS
TARGETING_USER_OS
TARGETING_USER_DEVICE
TARGETING_WIRELESS_CARRIER
TARGETING_EDUCATION_SCHOOLS
TARGETING_EDUCATION_STATUSES
TARGETING_COLLEGE_YEARS
TARGETING_EDUCATION_MAJORS
TARGETING_WORK_EMPLOYERS
TARGETING_WORK_POSITIONS
TARGETING_LOCALES
TARGETING_USER_ADCLUSTERS
TARGETING_FLEXIBLE_SPEC
TARGETING_EXCLUSIONS
TARGETING_GEO_LOCATIONS_COUNTRIES
TARGETING_GEO_LOCATIONS_REGIONS
TARGETING_GEO_LOCATIONS_CITIES
TARGETING_GEO_LOCATIONS_ZIPS
TARGETING_GEO_LOCATIONS_PLACES
TARGETING_GEO_LOCATIONS_CUSTOM_LOCATIONS
TARGETING_GEO_LOCATIONS_GEO_MARKETS
TARGETING_GEO_LOCATIONS_ELECTORAL_DISTRICT
TARGETING_GEO_LOCATIONS_LOCATION_TYPES
TARGETING_GEO_LOCATIONS_COUNTRY_GROUPS
TARGETING_EXCLUDED_GEO_LOCATIONS_COUNTRIES
TARGETING_EXCLUDED_GEO_LOCATIONS_REGIONS
TARGETING_EXCLUDED_GEO_LOCATIONS_CITIES
TARGETING_EXCLUDED_GEO_LOCATIONS_ZIPS
TARGETING_EXCLUDED_GEO_LOCATIONS_PLACES
TARGETING_EXCLUDED_GEO_LOCATIONS_CUSTOM_LOCATIONS
TARGETING_EXCLUDED_GEO_LOCATIONS_GEO_MARKETS
TARGETING_EXCLUDED_GEO_LOCATIONS_ELECTORAL_DISTRICT
TARGETING_EXCLUDED_GEO_LOCATIONS_LOCATION_TYPES
TARGETING_EXCLUDED_GEO_LOCATIONS_COUNTRY_GROUPS
ADSET_SOURCE_ID
BID_AMOUNT
BID_INFO_ACTIONS
BID_INFO_IMPRESSIONS
BID_STRATEGY
LIFETIME_MIN_SPEND_TARGET
LIFETIME_SPEND_CAP
PROMOTED_OBJECT_APPLICATION_TYPE
PROMOTED_OBJECT_CUSTOM_CONVERSION_ID
PROMOTED_OBJECT_CUSTOM_EVENT_STR
PROMOTED_OBJECT_CUSTOM_EVENT_TYPE
PROMOTED_OBJECT_EVENT_ID
PROMOTED_OBJECT_OBJECT_STORE_URL
PROMOTED_OBJECT_OFFER_ID
PROMOTED_OBJECT_OFFLINE_CONVERSION_DATA_SET_ID
PROMOTED_OBJECT_PAGE_ID
PROMOTED_OBJECT_PIXEL_AGGREGATION_RULE
PROMOTED_OBJECT_PIXEL_ID
PROMOTED_OBJECT_PIXEL_RULE
PROMOTED_OBJECT_PLACE_PAGE_SET_ID
PROMOTED_OBJECT_PRODUCT_CATALOG_ID
PROMOTED_OBJECT_PRODUCT_SET_ID
PROMOTED_OBJECT_RETENTION_DAYS*/


{% for column_name in promoted_object_list %}
PROMOTED_OBJECT:{{column_name}}::varchar as "PROMOTED_OBJECT_{{column_name}}"{%- if not loop.last %},{% endif -%}
{% endfor %},

{% for column_name in attribution_spec_list %}
ATTRIBUTION_SPEC:{{column_name}}::varchar as "ATTRIBUTION_SPEC_{{column_name}}"{%- if not loop.last %},{% endif -%}
{% endfor %},

{% for column_name in learning_stage_list %}
LEARNING_STAGE_INFO:{{column_name}}::varchar as "LEARNING_STAGE_INFO_{{column_name}}"{%- if not loop.last %},{% endif -%}
{% endfor %}


FROM {{ source('tap_facebook', 'adsets') }} as ad_set_history
