SELECT id as ad_id,
       TO_TIMESTAMP_NTZ(updated_time, 'YYYY-MM-DD"T"HH24:MI:SSTZHTZM') as ad_updated_time,
       index-1 as index,
       application,
       CAST(PARSE_JSON(value):"conversion_id" as variant) as conversion_id,
       PARSE_JSON(creative):id::number as creative,
       dataset,
       CAST(PARSE_JSON(value):"event" as variant) as event,
       CAST(PARSE_JSON(value):"event_type" as variant) as event_type,
       CAST(PARSE_JSON(value):"fb_pixel" as variant) as fb_pixel,
       CAST(PARSE_JSON(value):"fb_pixel_event" as variant) as fb_pixel_event,
       CAST(PARSE_JSON(value):"leadgen" as variant) as leadgen,
       CAST(PARSE_JSON(value):"object" as variant) as object,
       CAST(PARSE_JSON(value):"offer" as variant) as offer,
       CAST(PARSE_JSON(value):"offsite_pixel" as variant) as offsite_pixel,
       CAST(PARSE_JSON(value):"page" as variant) as page,
       CAST(PARSE_JSON(value):"post" as variant) as post,
       CAST(PARSE_JSON(value):"question" as variant) as question,
       CAST(PARSE_JSON(value):"response" as variant) as response,
       CAST(PARSE_JSON(value):"subtype" as variant) as subtype,
       CAST(PARSE_JSON(value):"action.type" as variant) as action_type,
       CAST(PARSE_JSON(value):"event_creator" as variant) as event_creator,
       CAST(PARSE_JSON(value):"object_domain" as variant) as object_domain,
       CAST(PARSE_JSON(value):"offer_creator" as variant) as offer_creator,
       CAST(PARSE_JSON(value):"page_parent" as variant) as page_parent,
       CAST(PARSE_JSON(value):"post_object_wall" as variant) as post_object_wall,
       CAST(PARSE_JSON(value):"post_wall" as variant) as post_wall,
       CAST(PARSE_JSON(value):"post_object" as variant) as post_object,
       CAST(PARSE_JSON(value):"question_creator" as variant) as question_creator,
       _sdc_batched_at

FROM {{ source('tap_facebook', 'ads') }},
lateral split_to_table(input=>ARRAY_TO_STRING(PARSE_JSON(tracking_specs), '|'), '|') tracking_columns