{{
   config(
     materialized='table'
   )
}}
 
SELECT ID,
       ACCOUNT_ID,
       EXTERNAL_EVENT_SOURCE_AUTOMATIC_MATCHING_FIELDS,
       EXTERNAL_EVENT_SOURCE_CAN_PROXY,
       EXTERNAL_EVENT_SOURCE_CODE,
       EXTERNAL_EVENT_SOURCE_CREATION_TIME,
       EXTERNAL_EVENT_SOURCE_DATA_USE_SETTING,
       EXTERNAL_EVENT_SOURCE_ENABLE_AUTOMATIC_MATCHING,
       EXTERNAL_EVENT_SOURCE_FIRST_PARTY_COOKIE_STATUS,
       EXTERNAL_EVENT_SOURCE_ID,
       EXTERNAL_EVENT_SOURCE_IS_CREATED_BY_BUSINESS,
       EXTERNAL_EVENT_SOURCE_IS_CRM,
       EXTERNAL_EVENT_SOURCE_IS_UNAVAILABLE,
       EXTERNAL_EVENT_SOURCE_LAST_FIRED_TIME,
       EXTERNAL_EVENT_SOURCE_NAME,
       LOOKALIKE_COUNTRY,
       LOOKALIKE_IS_FINANCIAL_SERVICE,
       LOOKALIKE_ORIGIN_EVENT_NAME,
       LOOKALIKE_ORIGIN_EVENT_SOURCE_NAME,
       LOOKALIKE_PRODUCT_SET_NAME,
       CAST(LOOKALIKE_RATIO as float) as LOOKALIKE_RATIO,
       CAST(LOOKALIKE_STARTING_RATIO as float) as LOOKALIKE_STARTING_RATIO,
       LOOKALIKE_TYPE,
       RULE_AGGREGATION

FROM {{ source('tap_facebook', 'customaudiences') }} as meltano_custom_audiences
